#pragma once

#define PLOOPY_DPI_OPTIONS {300, 800}
#define PLOOPY_DPI_DEFAULT 1

#undef PLOOPY_DRAGSCROLL_MOMENTARY
#define PLOOPY_DRAGSCROLL_INVERT 1
#define PLOOPY_DRAGSCROLL_DIVISOR_H 16.0
#define PLOOPY_DRAGSCROLL_DIVISOR_V 16.0